from fastapi import APIRouter
from app.db import get_connection

router = APIRouter()

# Crear tabla si no existe
@router.post("/init-db")
def init_db():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE '
            CREATE TABLE test_table (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(50)
            )';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
    """)
    conn.commit()
    cursor.close()
    conn.close()
    return {"status": "Tabla creada o ya existía"}

# Insertar un registro
@router.post("/insert")
def insert_record(name: str):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT INTO test_table (name) VALUES (:name)", [name])
    conn.commit()
    cursor.close()
    conn.close()
    return {"status": f"Registro '{name}' insertado"}

# Consultar registros
@router.get("/records")
def get_records():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT id, name FROM test_table")
    rows = cursor.fetchall()
    cursor.close()
    conn.close()
    return {"records": [{"id": r[0], "name": r[1]} for r in rows]}
